version: '3.8'
services:
  api:
    build: ./app
    volumes:
      - ./app:/code
    environment:
      FLASK_APP: ./backend/server.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: 1
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    ports:
      - 5000:5000
    command: bash -c "pip3 install . && flask run"
  postgres:
    image: postgres:12.15
    restart: always
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"
