version: '3.8'
services:
  api:
    build: .
    image: monolith:1
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    ports:
      - 5000:5000
