version: '3.8'
services:
  api:
    build: ./app
    volumes:
      - .:/code
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    command: bash -c "pip3 install ./app && pytest ./app/tests"
  postgres:
    image: postgres:12.15
    restart: always
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
